#!/bin/sh

OSNAME=$(uname)
VER='2.0.4'

if [ "$OSNAME" = "AIX" ]
then

	echo '.svn' > /tmp/xcat-excludes
    tar -X /tmp/xcat-excludes -cf /opt/freeware/src/packages/SOURCES/xCAT-server-$VER.tar xCAT-server
    gzip -f /opt/freeware/src/packages/SOURCES/xCAT-server-$VER.tar
    cd ./xCAT-server
    rm -f /opt/freeware/src/packages/SRPMS/xCAT-server-2.0*rpm /opt/freeware/src/packages/RPMS/ppc/xCAT-server-2.0*rpm
    rpm -ba xCAT-server.spec
    #rpm -Uvh /opt/freeware/src/packages/RPMS/ppc/xCAT-server-2.0*rpm

else

	if [ -f /etc/redhat-release ]
	then
   		pkg="redhat"
	else
   		pkg="packages"
	fi

	tar  --exclude .svn -czf /usr/src/$pkg/SOURCES/xCAT-server-$VER.tar.gz xCAT-server;
	rm -f /usr/src/$pkg/SRPMS/xCAT-server-2.0*rpm /usr/src/$pkg/RPMS/noarch/xCAT-server-2.0*rpm
	rpmbuild -ta /usr/src/$pkg/SOURCES/xCAT-server-$VER.tar.gz ;
	#rpm -Uvh /usr/src/$pkg/RPMS/noarch/xCAT-server-2.0*rpm
fi
